PartnerDemo/src/objects/Account_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Settings</relationshipLabel>
        <relationshipName>Account_Settings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Copyright_Text__c</fullName>
        <label>Copyright Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Items_Per_Page__c</fullName>
        <defaultValue>5</defaultValue>
        <label>No of Items Per Page</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Account Settings</relationshipLabel>
        <relationshipName>Account_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Icon_Options__c</fullName>
        <label>User Icon Options</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Setting</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Account Setting Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartnerDemo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>JBL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harman Kardon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Family</controllingField>
            <picklistValues>
                <fullName>Over Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Microphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sounds Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wireless Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stand-Alone Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom-Install Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subwoofers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amplifiers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connected Car</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>MID(Image_URL__c, 33, 55)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <description>Available stock of the product</description>
        <label>Stock</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

PartnerDemo/src/classes/prosearchcontroller2.cls
public with sharing class prosearchcontroller2 { 
   
   public prosearchcontroller2(portal_menuCls controller) {}
   public String accountId{get;set;}
   public static Account_Setting__c aSet{get;set;}
   public List <Product2> pro {get;set;}  
   public string search {get;set;}   
   public String priceBookId{get;set;}
   public string searchText {get;set;}   
   public static String selectedPrdId{get;set;}
   
    public prosearchcontroller2() { 
        getSearchResults();                                   
       }
     
    public String getsearchText()
    {return 'searchText';}
    public void setsearchText(String searchText)
    {
        this.searchText = searchText;
        system.debug('***1'+searchtext);
    }   
    
   /*public PageReference search(){  
      String searchText = Apexpages.currentPage().getParameters().get('searchText');
      system.debug('@@@@@4'+searchText);
      system.debug('@@@@@5'+search);
      //getSearchResults();
       return null;
   }*/
   
   public PageReference getSearchResults(){
       pro= new List<Product2>();
           accountId='0013600000SAesPAAT';
           String searchText = Apexpages.currentPage().getParameters().get('searchText');
            //searchText='jbl';
           system.debug('accountId------------------:'+accountId+searchText);
           system.debug('searchstring in search method:'+searchText );
           if(searchText!=null && searchText !=''){
            aSet= [SELECT Account__c,Copyright_Text__c,Id,Image_URL__c,is_Active__c,Name,No_of_Items_Per_Page__c,Price_Book__c,Theme__c,User_Icon_Options__c FROM Account_Setting__c where Account__c=:accountId and is_Active__c=true limit 1];
             if(aSet.Price_Book__c!=null){
                  priceBookId= aSet.Price_Book__c;               
                 //string search='SELECT Id,name,ProductCode,UnitPrice,Product2.Description,Product2.Name,Product2.Image__c,product2.Price__c,Product2.Category__c,Product2.Brand__c,Product2.Stock__c,Product2.isActive,Product2.Family FROM PricebookEntry where  product2.name=JBL Horizon limit 4 ';
                 string searchQuery='select id,name,Stock__c,RecordTypeId,(SELECT Id,UnitPrice,Pricebook2Id,Product2Id FROM PricebookEntries where Pricebook2Id=:priceBookId limit 1),RecordType.DeveloperName,Family,Description,ProductCode,Price__c,image_URL__c,Image__c from Product2 where IsActive=true and product2.name like \'%'+searchText +'%\' Limit 20';//searchText 
                 system.debug('searchQuery:'+searchQuery);   
                 pro= Database.query(searchQuery);
                 system.debug('#####5'+pro); 
                 if(pro.size()<=0)
                   {
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'No Records are found'));
                        return null; 
                        
                    }
                   
                           
               }
           }  
          
             
             else        
               {
               system.debug('NOT FOUND');
               ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'Enter searchstring'));
                return null;

               }
          
           return null;
   }
   
       public static PageReference insertQuantity(){ 
        aSet= new Account_Setting__c ();       
        Portal_globalClass globalObj = new Portal_globalClass();
        aSet= Portal_globalClass.aSet;
        System.debug('Ajayyyyy'+selectedPrdId);
        if(selectedPrdId!=''){
             System.debug('Ajayyyyy'+aSet.price_Book__c);
             Portal_globalClass.insertToCart(selectedPrdId,aSet.price_Book__c);
        }
        
        return null;
    }
      
 }