PartnerDemo/src/objects/Account_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Settings</relationshipLabel>
        <relationshipName>Account_Settings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Copyright_Text__c</fullName>
        <label>Copyright Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Footer_Links__c</fullName>
        <label>Footer Links</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Items_Per_Page__c</fullName>
        <defaultValue>5</defaultValue>
        <label>No of Items Per Page</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Theme__c</fullName>
        <label>Theme</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black</fullName>
                <isActive>false</isActive>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Icon_Options__c</fullName>
        <label>User Icon Options</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Setting</label>
    <nameField>
        <displayFormat>AS-{0000}</displayFormat>
        <label>Account Setting Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartnerDemo/src/objects/Tab_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tab Settings</relationshipLabel>
        <relationshipName>Tab_Settings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submenus_for_Tab__c</fullName>
        <label>Submenus for Tab</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tab_Name__c</fullName>
        <label>Tab Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tab_URL__c</fullName>
        <label>Tab URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Tab Setting</label>
    <nameField>
        <displayFormat>Tab Setting-{0000}</displayFormat>
        <label>Tab Setting</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tab Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartnerDemo/src/classes/ECommerce_CofigurableClass.cls
public class ECommerce_CofigurableClass{
    
    public Account_Setting__c accSet{get;set;}
    public List<Tab_Setting__c> tabSet{get;set;}
    public String partnerBrandLogo;
    public String partnerTheme;
    public String footerLinkHeader{get;set;}
    public List<String> footerLinks{get;set;}   
    public List<String> iconOptions{get;set;} 
    
    public Map<Integer,Map<String,List<String>>> getTabNames(Id accId){
        System.debug('000000000'+accId);
        Map<Integer,Map<String,List<String>>> tabsMap = new Map<Integer,Map<String,List<String>>>();
        accSet = new Account_Setting__c();        
        accSet=[select id,Account__c,Image_URL__c,Theme__c,Copyright_Text__c,Footer_Links__c,is_Active__c,No_of_Items_Per_Page__c,User_Icon_Options__c from Account_Setting__c where Account__c=:accId and is_Active__c=true limit 1];
        tabSet=[SELECT Account__c,Display_Order__c,Id,is_Active__c,Name,Submenus_for_Tab__c,Tab_Name__c,Tab_URL__c FROM Tab_Setting__c where Account__c=:accId and is_Active__c=true limit 6];        
        
        
        if(accSet!=null && !String.isBlank(accSet.Image_URL__c) && !String.isBlank(accSet.Theme__c)){
            partnerBrandLogo = accSet.Image_URL__c;        
            partnerTheme = accSet.Theme__c;
            if(!String.isBlank(accSet.Footer_Links__c)){
                footerLinks = accSet.Footer_Links__c.split(';');
                footerLinkHeader= footerLinks[0];
                footerLinks.remove(0);
            }
            if(!String.isBlank(accSet.User_Icon_Options__c)){
                iconOptions = accSet.User_Icon_Options__c.split(';');
            }
        }        
        
        for(Tab_Setting__c tabS:tabSet){
            Map<String,List<String>> tempMenuList = new Map<String,List<String>>();
            List<String> menuList = new List<String>();
            if(!String.isBlank(tabS.Tab_Name__c) && !String.isBlank(tabS.Submenus_for_Tab__c)){
                menuList=tabS.Submenus_for_Tab__c.split(';');  
                tempMenuList.put(tabS.Tab_Name__c,menuList);                            
            }else if(!String.isBlank(tabS.Tab_Name__c)){
                 tempMenuList.put(tabS.Tab_Name__c,menuList);  
            }
             
            tabsMap.put(Integer.valueOf(tabS.Display_Order__c),tempMenuList); 
             
        }
        
       
        System.debug('%%%%%'+tabsMap);
        return tabsMap;
    }  
        
}