PartnerDemo/src/objects/Hard_Coded_Labels__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Hard Coded Labels</label>
</CustomObject>

PartnerDemo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>JBL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harman Kardon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Family</controllingField>
            <picklistValues>
                <fullName>Over Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Microphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sounds Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wireless Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stand-Alone Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom-Install Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subwoofers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amplifiers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connected Car</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>MID(Image_URL__c, 33, 55)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <description>Available stock of the product</description>
        <label>Stock</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

PartnerDemo/src/classes/FileUploadController.cls
public with sharing class FileUploadController {

    public String selectedValue { get; set; }    
    public Transient blob picture { get; set; }
    public String errorMessage { get; set; }
    public Product2 product { get; set; }
    public static List<Product2> products = new List<Product2>(); 
    public Map<string,Hard_Coded_Labels__c> mapLabels{get;set;}
    public boolean  isLive {get;set;} 
    //public Transient String picture {get;set;}
    public String filename{get;set;}
        
  public static List<SelectOption> ProductsList
    {
        get
        {
             products = [SELECT Id,Name FROM Product2];
             ProductsList = new List<SelectOption>();
             ProductsList.add(new SelectOption('--None--','--None--'));
            for(Product2 temp : products )
               {
                    ProductsList.add(new SelectOption(temp.Id, temp.Name));
                }
            return ProductsList;
        }
        set;
    }
    
   public PageReference getProdDetails(){
       isLive=true;
     system.debug('inside getprodetails');
     try{
     product = [SELECT Brand__c,Category__c,CreatedById,Stock__c,CreatedDate,Description,Family,Id,Image_URL__c,Image__c,IsActive,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Name,Price__c,
                     ProductCode,RecordTypeId,SystemModstamp FROM Product2 WHERE Id = :selectedValue];
    
     }catch(Exception e){
         product = new Product2();
     }
      return null;
   }
   public PageReference save() {
    errorMessage = '';
    mapLabels = Hard_Coded_Labels__c.getAll();
     
    Attachment attachment = new Attachment();    
    try {
         Product2 product1 = [SELECT Brand__c,Category__c,Stock__c,CreatedById,CreatedDate,Description,Family,Id,Image_URL__c,Image__c,IsActive,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Name,Price__c,
                     ProductCode,RecordTypeId,SystemModstamp FROM Product2 WHERE Id = :selectedValue];
       // upsert product;
        if (picture != null) {                    
            attachment.body = picture;//Blob.valueOf(picture);//
            system.debug('file size:  '+attachment.body.size());
            if(attachment.body.size()>135000)
                {
                     ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,mapLabels.get('FileUpload_MaxLimit').Value__c));   
                     return null;       
                }
                else{
                    attachment.name = 'product_' + fileName;            
                    attachment.parentid = selectedValue;
                    //attachment.Title='DisplayImage';
                    attachment.ContentType = 'application/jpg';            
                    insert attachment;
                    product1.Image_URL__c = '/servlet/servlet.FileDownload?file='+ attachment.id; 
                    product1.Brand__c=product.Brand__c;
                    product1.Category__c=product.Category__c;
                    product1.Family=product.Family;
                    product1.IsActive=product.IsActive;
                    product1.Price__C=product.Price__C;
                    product1.Stock__c=product.Stock__c;           
                    update product1 ;                    
            }
        }       
    }
    catch (DMLException e) {
        system.debug('Error uploading attachment');
        errorMessage = e.getMessage();
      ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,mapLabels.get('FileUpload_Error').Value__c));
      return null;
    } 
      catch(System.Exception ex) {      
        errorMessage = ex.getMessage();
        system.debug('Error uploading attachment:'+errorMessage );
        return null;

    }
    finally {
      attachment = new Attachment(); 
    }
    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,mapLabels.get('Fileupload_Success').Value__c));
     system.debug('Attachment uploaded successfully');
    return null;
    }

}