PartnerDemo/src/objects/OrderItem.object
<CustomObject>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>UnitPrice *  Quantity</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

PartnerDemo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
</CustomObject>

PartnerDemo/src/classes/OrderListController.cls
public  class OrderListController
{
     public Id orderId{get;set;}
     
     Public List<OrderItem> getordProducts()
     {
         List<OrderItem> ordPro;
         ordPro = [SELECT Id, OrderId, OrderItemNumber, PricebookEntry.Product2.Name,PricebookEntry.Product2.Image_Url__c, PricebookEntry.Product2.Productcode, Quantity, UnitPrice, Total_Price__c FROM OrderItem ];
         return ordpro;
     }
     
}