PartnerDemo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>JBL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harman Kardon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Family</controllingField>
            <picklistValues>
                <fullName>Over Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Microphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sounds Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wireless Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stand-Alone Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom-Install Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subwoofers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amplifiers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connected Car</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>MID(Image_URL__c, 33, 55)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
</CustomObject>

PartnerDemo/src/classes/SearchController5.cls
public class SearchController5{
      public String productName { get; set; }    
      //public static List<Product2> prodList{get;set;}
      //public SearchController4() { } // empty constructor
  
/*public static List<Product2> getProducts1() {
        prodList= [SELECT Brand__c,Category__c,Family,Id,Image_URL__c,Image__c FROM Product2 WHERE Family = 'Headphones'];
        return prodList;
    }*/
     public List<Product2> products = new List<Product2>();   
  
  public List<SelectOption> ProductsList
    {
        get
        {
             products = [SELECT Id,Name,family FROM Product2];
             ProductsList = new List<SelectOption>();
            for(Product2 temp : products )
               {
                    ProductsList.add(new SelectOption(temp.Id, temp.Name));
                }
                system.debug('++showing'+ProductsList);
            return ProductsList;
        }
        set;
    }
    public pageReference getProducts()
    {    
      //getProducts1();
      return null;
    }


}