PartnerDemo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>JBL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harman Kardon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Family</controllingField>
            <picklistValues>
                <fullName>Over Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Microphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sounds Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wireless Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stand-Alone Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom-Install Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subwoofers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amplifiers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connected Car</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>MID(Image_URL__c, 33, 55)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

PartnerDemo/src/classes/FileUploadController1.cls
public with sharing class FileUploadController1 {

    public String selectedValue { get; set; }
    
    public blob picture { get; set; }

    public String errorMessage { get; set; }
    public string searchstring {get;set;}  
    private Product2 product;
    private final String productId='01t36000002Fkta';

public List<Product2> products3 {get; set;} 
 public List<Product2> products = new List<Product2>();   
 public List<Product2> products1 {get; set;} 
 
  public List<SelectOption> ProductsList
    {
        get
        {
             products = [SELECT Id,Name FROM Product2];
             ProductsList = new List<SelectOption>();
            for(Product2 temp : products )
               {
                    ProductsList.add(new SelectOption(temp.Id, temp.Name));
                }
            return ProductsList;
        }
        set;
    }
 public PageReference search() 
    {
       
      System.debug('searchstring:'+searchstring);
      //products1 =[SELECT Description, Family, Id, Image_URL__c, Image__c FROM Product2 WHERE Family LIKE' + '\'%' + searchstring + '%\' LIMIT 2 ]; 
     products1 = Database.query('SELECT  Description, Family, Id, Image_URL__c, Image__c FROM Product2 WHERE Family LIKE' + '\'%' + searchstring + '%\'');
      System.debug('products1 :'+products1 ); 
     //Product3= Database.query(products1);  
     return null;
       
    }
     
  
  
   public PageReference save() {
    errorMessage = '';
    try {
    System.debug('selectedValue :'+selectedValue );
    // product = [SELECT Brand__c,Category__c,CreatedById,CreatedDate,Description,Family,Id,Image_URL__c,Image__c,IsActive,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Name,Price__c,ProductCode,RecordTypeId,SystemModstamp FROM Product2 WHERE Id = '01t360000017xd4' ];
       // upsert product;
      product = [SELECT Brand__c,Category__c,CreatedById,CreatedDate,Description,Family,Id,Image_URL__c,Image__c,IsActive,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Name,Price__c,ProductCode,RecordTypeId,SystemModstamp FROM Product2 WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
        if (picture != null) { 
            Attachment attachment = new Attachment();
            attachment.body = picture;
            attachment.name = 'product_' + productId + '.jpg';
            attachment.parentid = productId;
           attachment.ContentType = 'application/jpg';
            insert attachment;
            product.Image_URL__c = 'https://c.na30.content.force.com/servlet/servlet.FileDownload?file='+ attachment.id;
            product.Price__c =13000.00;
            update product;
        }
        return null;
    } catch(System.Exception ex) {
        errorMessage = ex.getMessage();
        return null;

    }
}
}