PartnerDemo/src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <picklist>
            <picklistValues>
                <fullName>JBL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Harman Kardon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AKG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Infinity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <controllingField>Family</controllingField>
            <picklistValues>
                <fullName>Over Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Ear</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>With Microphone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Theater</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sounds Bar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wireless Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stand-Alone Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Custom-Install Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Speakers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subwoofers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amplifiers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component Systems</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connected Car</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <formula>MID(Image_URL__c, 33, 55)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Image</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stock__c</fullName>
        <description>Available stock of the product</description>
        <label>Stock</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

PartnerDemo/src/classes/ProductBrowserController.cls
public with sharing class ProductBrowserController {
public static final Integer PAGE_SIZE = 10;  
public static Apexpages.Standardsetcontroller setCon {  
      get {  
           if(setCon == null){  
                String query = 'SELECT Brand__c,Category__c,CreatedById,CreatedDate,Description,Family,Id,Image_URL__c,Image__c,IsActive,IsDeleted,LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Name,Price__c,ProductCode,RecordTypeId,Stock__c,SystemModstamp FROM Product2 ORDER BY Name ASC';  
                setCon = new Apexpages.Standardsetcontroller(Database.getQueryLocator(query));  
           }  
           return setCon;  
      }  
      set;  
 } 
 
 
  public static AccountWrapper buildScrollData(Integer currentPageNumber, Boolean getMore){  
       if(setCon != null){  
            setCon.setPageSize(PAGE_SIZE);  
            setCon.setPageNumber(currentPageNumber);  
          if(getMore){  
                if(setCon.getHasNext()){  
                    setCon.next();  
                     List<Product2> accts = (List<Product2>)setCon.getRecords();  
                      if(accts != null && !accts.isEmpty()){  
                         AccountWrapper aw = new AccountWrapper(setCon.getPageNumber(), setCon.getHasNext(), true, accts);  
                          return aw;  
                     } else {  
                          AccountWrapper aw = new AccountWrapper(setCon.getPageNumber(), setCon.getHasNext(), false, null);  
                         return aw;  
                      }  
                } else {  
                      AccountWrapper aw = new AccountWrapper(setCon.getPageNumber(), setCon.getHasNext(), false, null);  
                      return aw;  
                 }  
           } else {  
                 //Initial Call. Load the first number or records according to pageSize  
                AccountWrapper aw = new AccountWrapper(setCon.getPageNumber(), setCon.getHasNext(), true, (List<Product2>)setCon.getRecords());  
                return aw;  
           }  
       }  
       return null;  
  }   
  
   public class AccountWrapper{  
       public Integer pageNumber { get; set; }  
       public Boolean hasMore { get; set; }  
       public Boolean noRecords { get; set; }  
       public List<Product2> records { get; set; }  
       public AccountWrapper(Integer currentPageNumber, Boolean more, Boolean noRecs, List<Product2> recordsForSinglePage){  
            pageNumber = currentPageNumber;  
            hasMore = more;  
            noRecords = noRecs;  
            records = recordsForSinglePage;  
       }  
  } 
   public static String accountList {  
       get {  
            AccountWrapper aw = buildScrollData(1, false);  
           accountList = JSON.serialize(aw);  
            return accountList;  
       }  
     private set;  
  } 
 @RemoteAction  
  public static ProductBrowserController.AccountWrapper getMore(String currentPageNumber, String hasMore){  
       Integer pageNumber = Integer.valueOf(currentPageNumber);  
      Boolean more = Boolean.valueOf(hasMore);  
       if(more){  
            ProductBrowserController.AccountWrapper aw = ProductBrowserController.buildScrollData(pageNumber, more);  
            return aw;  
       }  
       return null;  
  }
 }